```{r}
library(tidyverse)
library(jsonlite)
library(mapdeck)
```

```{r}
mapbox <- read_json("../data/mapbox.json")
set_token(mapbox$token)
```

```{r}
# hop_teaming_providers <- read_csv("../data/hop_teaming_providers_filtered.csv", show_col_types = F)
# addresses <- read_csv("../data/tn_team_hopping_addresses.csv", show_col_types = F)
```

```{r}
# npi_lat_long <- providers %>% 
#   inner_join(addresses %>% drop_na(geo_address),
#              by = c("address_first_line", 
#                     "address_second_line", 
#                     "city", 
#                     "state", 
#                     "zipcode")) %>%
#   select(npi, lat, long)
# 
# write_csv(npi_lat_long, "../data/npi_lat_long.csv")
```

```{r}
# mapdeck(style = mapdeck_style("light"), pitch = 60) %>%
#   add_animated_arc(
#     data = hop_teaming_lat_long %>% sample_n(500), 
#     layer_id = "arc_layer", 
#     origin = c("from_long", "from_lat"), 
#     destination = c("to_long", "to_lat"), 
#     stroke_from = "from_npi", 
#     stroke_to = "to_npi",
#     stroke_width = 1,
#     brush_radius = 80467)
```

```{r}
hop_teaming_provider_to_facility_patient_counts <- read_csv("../data/hop_teaming_provider_to_facility_patient_counts.csv", show_col_types = F)
npi_lat_long <- read_csv("../data/npi_lat_long.csv", show_col_types = F)
```

```{r}
orthopaedic_arc_layer <- hop_teaming_provider_to_facility_patient_counts %>% 
  filter(
    # from_cbsa == 34980,
    to_affiliation %in% c("VUMC", "HCA", "ASCENSION SAINT THOMAS", "LIFEPOINT", "CHS"),
    from_specialty == "Orthopaedic Surgery") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("from_", .x)), by = "from_npi") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("to_", .x)), by = "to_npi") %>%
  mutate(from_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d01",
                              to_affiliation == "HCA" ~ "#e2592901",
                              to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429701",
                              to_affiliation == "LIFEPOINT" ~ "#5f606201"),
         to_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d30",
                            to_affiliation == "HCA" ~ "#e2592930",
                            to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429730",
                            to_affiliation == "LIFEPOINT" ~ "#5f606230"))
```

```{r}
orthopaedic_grid_layer <- orthopaedic_arc_layer %>% 
  group_by(from_lat, from_long, to_affiliation) %>%
  summarize(patients = sum(patients), .groups = "drop") %>%
  arrange(desc(patients)) %>%
  uncount(patients)
```

```{r}
orthopaedic_scale_factor <- orthopaedic_arc_layer %>% 
  group_by(from_lat, from_long, to_affiliation) %>%
  summarize(patients = sum(patients)) %>%
  group_by(to_affiliation) %>%
  summarize(patients = max(patients))

orthopaedic_vumc <- orthopaedic_scale_factor %>% 
  filter(to_affiliation == "VUMC") %>% 
  pull(patients) / 10000
orthopaedic_hca <- orthopaedic_scale_factor %>% 
  filter(to_affiliation == "HCA") %>% 
  pull(patients) / 10000
orthopaedic_ascension <- orthopaedic_scale_factor %>% 
  filter(to_affiliation == "ASCENSION SAINT THOMAS") %>% 
  pull(patients) / 10000
orthopaedic_lifepoint <- orthopaedic_scale_factor %>% 
  filter(to_affiliation == "LIFEPOINT") %>% 
  pull(patients) / 10000
```

```{r}
mapdeck(style = mapdeck_style("dark"), pitch = 60) %>%
  add_animated_arc(
    data = orthopaedic_arc_layer,
    layer_id = "arc_layer",
    origin = c("from_long", "from_lat"),
    destination = c("to_long", "to_lat"),
    stroke_from = "from_hex",
    stroke_to = "to_hex",
    animation_speed = 0.1,
    stroke_width = 3) %>%
  add_grid(
    data = orthopaedic_grid_layer %>% filter(to_affiliation == "VUMC"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#9a783d","#9a783d","#9a783d","#9a783d","#9a783d","#9a783d"),
    cell_size = 750,
    elevation_scale = 50 * orthopaedic_vumc,
    layer_id = "VUMC") %>%
  add_grid(
    data = orthopaedic_grid_layer %>% filter(to_affiliation == "HCA"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#e25929","#e25929","#e25929","#e25929","#e25929","#e25929"),
    cell_size = 750,
    elevation_scale = 50 * orthopaedic_hca,
    layer_id = "HCA") %>%
  add_grid(
    data = orthopaedic_grid_layer %>% filter(to_affiliation == "ASCENSION SAINT THOMAS"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#1c4297","#1c4297","#1c4297","#1c4297","#1c4297","#1c4297"),
    cell_size = 750,
    elevation_scale = 50 * orthopaedic_ascension,
    layer_id = "ASCENSION SAINT THOMAS") %>%
  add_grid(
    data = orthopaedic_grid_layer %>% filter(to_affiliation == "LIFEPOINT"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#5f6062","#5f6062","#5f6062","#5f6062","#5f6062","#5f6062"),
    cell_size = 750,
    elevation_scale = 50 * orthopaedic_lifepoint,
    layer_id = "LIFEPOINT")
```

```{r}
family_arc_layer <- hop_teaming_provider_to_facility_patient_counts %>% 
  filter(
    # from_cbsa == 34980,
    to_affiliation %in% c("VUMC", "HCA", "ASCENSION SAINT THOMAS", "LIFEPOINT"),
    from_specialty == "Family Medicine") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("from_", .x)), by = "from_npi") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("to_", .x)), by = "to_npi") %>%
  mutate(from_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d01",
                              to_affiliation == "HCA" ~ "#e2592901",
                              to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429701",
                              to_affiliation == "LIFEPOINT" ~ "#5f606201"),
         to_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d30",
                            to_affiliation == "HCA" ~ "#e2592930",
                            to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429730",
                            to_affiliation == "LIFEPOINT" ~ "#5f606230"))
```

```{r}
family_grid_layer <- family_arc_layer %>% 
  group_by(from_lat, from_long, to_affiliation) %>%
  summarize(patients = sum(patients), .groups = "drop") %>%
  arrange(desc(patients)) %>%
  uncount(patients)
```

```{r}
family_scale_factor <- family_arc_layer %>% 
  group_by(from_lat, from_long, to_affiliation) %>%
  summarize(patients = sum(patients)) %>%
  group_by(to_affiliation) %>%
  summarize(patients = max(patients))

family_vumc <- family_scale_factor %>% 
  filter(to_affiliation == "VUMC") %>% 
  pull(patients) / 10000
family_hca <- family_scale_factor %>% 
  filter(to_affiliation == "HCA") %>% 
  pull(patients) / 10000
family_ascension <- family_scale_factor %>% 
  filter(to_affiliation == "ASCENSION SAINT THOMAS") %>% 
  pull(patients) / 10000
family_lifepoint <- family_scale_factor %>% 
  filter(to_affiliation == "LIFEPOINT") %>% 
  pull(patients) / 10000
```

```{r}
mapdeck(style = mapdeck_style("light"), pitch = 60,) %>%
  # add_animated_arc(
  #   data = family_arc_layer,
  #   layer_id = "arc_layer",
  #   origin = c("from_long", "from_lat"),
  #   destination = c("to_long", "to_lat"),
  #   stroke_from = "from_hex",
  #   stroke_to = "to_hex",
  #   animation_speed = 0.1,
  #   stroke_width = 3) %>%
  add_grid(
    data = family_grid_layer %>% filter(to_affiliation == "VUMC"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#9a783d","#9a783d","#9a783d","#9a783d","#9a783d","#9a783d"),
    cell_size = 750,
    elevation_scale = 50 * family_vumc,
    layer_id = "VUMC") %>%
  add_grid(
    data = family_grid_layer %>% filter(to_affiliation == "HCA"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#e25929","#e25929","#e25929","#e25929","#e25929","#e25929"),
    cell_size = 750,
    elevation_scale = 50 * family_hca,
    layer_id = "HCA") %>%
  add_grid(
    data = family_grid_layer %>% filter(to_affiliation == "ASCENSION SAINT THOMAS"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#1c4297","#1c4297","#1c4297","#1c4297","#1c4297","#1c4297"),
    cell_size = 750,
    elevation_scale = 50 * family_ascension,
    layer_id = "ASCENSION SAINT THOMAS") %>%
  add_grid(
    data = family_grid_layer %>% filter(to_affiliation == "LIFEPOINT"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#5f6062","#5f6062","#5f6062","#5f6062","#5f6062","#5f6062"),
    cell_size = 750,
    elevation_scale = 50 * family_lifepoint,
    layer_id = "LIFEPOINT")
```